base_url = "https://brvtalcake.github.io"
author = "Axel PASCON"
title = "brvtalcake's RootFS"
#title = "brvtalcake's rootfs"
description = "Where my thought trees grow."

compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = true
default_language = "en"
hard_link_static = true

theme = "apollo"

taxonomies = [
    { name = "tags" }
#    ,{ name = "language" }
]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
smart_punctuation = true
bottom_footnotes = true
highlight_code = true
#highlight_theme = "ayu-light"
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-light", filename = "syntax-theme-dark.css" },
  { theme = "ayu-dark", filename = "syntax-theme-light.css" },
]

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_view = true
repo_url = "https://github.com/brvtalcake/brvtalcake.github.io/tree/main/content/"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 }
    ,{ name = "/by-lang", url = "/by-language", weight = 5 }
]

socials = [
    { name = "instagram", url = "https://instagram.com/axel.pascon", icon = "instagram" },
    { name = "github", url = "https://github.com/brvtalcake/", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false

#[extra.analytics.goatcounter]
#user = "your_user"
#host = "example.com" # default= goatcounter.com
#
#[extra.analytics.umami]
#website_id = "43929cd1-1e83...."
#host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/


#[markdown]
## Whether to do syntax highlighting
## Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = true
#
#[extra]
## Put all your custom variables here
#theme = "auto"
#socials = [
#  # Configure socials here
#]
#menu = [
#  # Configure menu bar here
#]
#
## See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
